ryush00/capstone

app/views/devise/registrations/new.html.erb
=> 회원가입 아이디, 비밀번호, 비밀번호확인 name 값 수정

app/views/application/index.html.erb, app/views/devise/registrations/edit.html.erb
=> 내정보창_회원정보수정클릭_회원정보수정(users/edit)꾸미기

app/views/devise/passwords/new.html.erb, db/schema.rb
- 상단 div 태그 클래스에 mt-5 추가함
- 맨 밑에 <%= render "devise/shared/links" %>을 추가
- 
-
=> 마진 추가, 로그인 공통 링크추가

app/javascript/application.js
- 페이지 캐싱 오프캔버스가 안 닫히는 문제 수정
- 이제 뒤로가기 후 발생하는 문제가 수정되었습니다.
- fix #54
- 
-
=> fix: 오프캔버스가 안 닫히는 문제 수정

app/views/application/index.html.erb
출발지, 목적지 text -> select로 변경 , 최대 5명 상향, 문의 버튼 생성
- 
-
=>  출발지, 목적지 text -> select로 변경 , 최대 5명 상향, 문의 버튼 생성

app/views/application/index.html.erb
- 카풀 만들기 클릭 시 뜨는 창 투명화
- 카풀 찾기 클릭 시 뜨는 창 투명화
- 
-
=> 카풀만들기+카풀찾기_어두운 투명화&수정

app/models/place.rb, app/models/pool.rb, db/migrate/20241115172052_change_types_to_integer.rb, db/schema.rb
- pool_type, place_type을 string에서 int로 변경
- enum 추가
- 모델 검증 추가
- 
-
=> 데이터베이스 구조 변경 및 모델 검증 추가

app/controllers/application_controller.rb, app/views/application/index.html.erb, app/views/pools/_list.html.erb, app/views/pools/index.html.erb
- 카풀 만들기를 수정함(원래 있던 변수와 디스코드 때 배운 내용 중 변수를 사용)
- 카풀 찾기를 수정함(디스코드 때 배운 내용 중 변수를 사용)
- 
데이터 입력 전입니다.
-
데이터 입력 후 표에 표시됩니다.
- 디스코드로 배운 내용 응용해서 수정했습니다.
=> render 코드로 수정

app/controllers/pools_controller.rb, app/views/application/index.html.erb, app/views/pools/_list.html.erb, app/views/pools/show.html.erb, config/routes.rb
- 모집 마감 기능 추가
- 카풀 참가 기능 추가
- 오프캔버스 투명화 작업
- 
-
=> 모집 마감, 참가 기능 추가

app/controllers/places_controller.rb, app/controllers/pools_controller.rb
- 수정, 삭제 시 메시지 한글로 바꾸기 
- 
- fix #71
=> 수정, 삭제 시 메시지 한글로 바꾸기 

app/controllers/pools_controller.rb, app/views/pools/_form.html.erb
- 시간 입력 안받게 수정(모집시간=현재시간, 모집종료=현재시간+60분)
- 
-
=> 시간 입력 안받게 수정

app/views/application/index.html.erb
=> fix: 카풀 생성 폼이 잘리는 현상 수정

app/views/pools/_list.html.erb, app/views/pools/edit.html.erb, app/views/pools/index.html.erb, app/views/pools/new.html.erb, app/views/pools/show.html.erb
- 마감 버튼 위치 중앙 정렬 성공
- 나머지는 부트스트랩으로 꾸몄습니다.
- 
-
=> 카풀 pools 부트스트랩 수정 완료

db/migrate/20241119055815_add_admin_to_users.rb, db/schema.rb
- 유저 테이블에 admin 추가
- ㅁㅁㅁ을 수정함
- 
-
=> 유저 테이블 admin 추가

app/views/pools/_list.html.erb, app/views/pools/edit.html.erb, app/views/pools/index.html.erb, app/views/pools/new.html.erb, app/views/pools/show.html.erb
- pools 파일에 있는 카풀 목록, 카풀 수정, 카풀 생성 가로 폭 수정
- 추가로 a태그를 버튼으로 바꾸는 작업도 수행
- 
-
=> fix #82 카풀 생성 페이지 가로폭 줄이기 #82

app/views/layouts/application.html.erb
- fix: 페이지 첫 로드 시 오류 메시지 안 뜨는 문제 수정
- 
-
=> fix: 페이지 첫 로드 시 오류 메시지 안 뜨는 문제 수정

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> 로그인/회원가입/인증메일 사이트 디자인

app/controllers/application_controller.rb, app/controllers/places_controller.rb, app/views/layouts/application.html.erb
- 어드민을 관리자만 사용가능하게 수정함. 
- 
- fix #79
=> 컨트롤러들에 어드민 권한 적용하기

app/views/application/index.html.erb
- 네이버 지도로 변경
- 뒤로가기 시 지도 이상하게 뜨던 것 수정
- 
-
=> 네이버 지도로 지도 변경

app/views/pools/show.html.erb
taxi를 선택하면 택시 car를 선택하면 자동차가 나오도록 변경
=> 카풀 종류 제대로 뜨게 수정

app/controllers/pools_controller.rb, app/models/pool.rb, app/views/pools/show.html.erb
- 방장에 권한 부여
- 팀원은 권한 x
- 
- fix #87
=> 카풀 삭제, 수정, 모집 마감 권한 확인 #87

app/views/application/index.html.erb, app/views/pools/_list.html.erb, app/views/pools/new.html.erb
=> 처음처럼 (홈으로 가는 버튼 생성)

app/views/application/index.html.erb, app/views/layouts/application.html.erb
=> 문의 생성 (문의 누르면 채널톡 나옴)

app/views/application/index.html.erb
=> 로그인 두번 눌러야 하는 것 고침.

app/controllers/pools_controller.rb, app/views/pools/_list.html.erb, app/views/pools/show.html.erb
카풀 생성 시 제목 만들기
카풀 목록에 제목 띄우기
카풀 정보에 제목 띄우기
- 
-
=> 카풀 목록, 정보에 카풀명 띄우기

Gemfile, Gemfile.lock, app/controllers/pools_controller.rb, app/helpers/application_helper.rb, app/views/application/index.html.erb, app/views/pools/_list.html.erb, app/views/pools/show.html.erb, config/initializers/pagy.rb
=> 참가 완료 하면 이미참가된상태 나타내게

app/views/pools/_list.html.erb, app/views/pools/new.html.erb
- 카풀 목록에서 참가 중 일 때, 참여 중 버튼 표시
- 
- fix
=> 목록에서 참가 했음에도 참가하기 버튼이 뜨는 문제 #122

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_logo.html.erb
=> 로그인창에서 처음화면 전환하기

app/controllers/pools_controller.rb, app/views/pools/_list.html.erb
- 목록을 반응형으로 변경
- 한페이지에 10->9개로 보이도록 변경.
- 
- close #126
=> 카풀 목록 반응형 디자인

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb
=> 이메일을 영어에서 한글로 바꿈

fly.toml
- 서버가 정지되지 않고 일시 정지 (suspend) 되도록 수정
- 
- https://community.fly.io/t/autosuspend-is-here-machine-suspension-is-enabled-everywhere/20942
=> feat: 서버가 suspend되도록 수정

app/views/application/index.html.erb
- 마커 창 테두리 제거 후 디자인(임시)
- 
- fix  #155
=> fix: 지도 마커 디자인 개선

app/views/application/index.html.erb, app/views/layouts/application.html.erb
- 메인 페이지가 아닌 다른 페이지에서 사이트를 새로고침하고 메인 페이지로 이동하게 되면 지도가 로드되지 않던 현상 수정
- 
- fix #150
=> fix: 메인 페이지에서 시작 안하면 지도가 흰색으로 뜨던 현상 수정

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pools/edit.html.erb, app/views/pools/index.html.erb, app/views/pools/new.html.erb, app/views/pools/show.html.erb
=> fix: 제목 올바르게 바꾸기

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pools/index.html.erb
로그인 회원가입 로고 추가, 카풀 목록 칸 띄우기
- 
- fix : #161
=> 로그인 회원가입 로고 추가, 카풀 목록 칸 띄우기

config/initializers/devise.rb
=> feat: 이메일 주소 변경

Gemfile, Gemfile.lock, config/cable.yml, config/database.yml, db/cable_schema.rb
=> feat: SolidCable 추가

app/models/booking.rb, app/models/pool.rb, app/views/pools/_bookings.html.erb, app/views/pools/_pool_table.html.erb, app/views/pools/show.html.erb
=> feat: 실시간 업데이트 추가
